### ISSUE TITLE
Add Missing Translations and Standardize Translation Management Across GhostBSD Python Repositories  

### ISSUE THREAD

**Issue by ericbsd** [ghostbsd/issues#196]
**Description:**  
To improve and streamline translation workflows across GhostBSD Python repositories, we need to:  
1. Add missing translations to repositories that currently lack `gettext` support.  
2. Standardize the creation and maintenance of translations using commands like `create_translation` and `update_translations`.  
3. Use the **update-station** repository as a reference for integrating and managing translations efficiently.  

The goal is to make translations more straightforward to manage and ensure consistency across all GhostBSD Python projects.

**Repositories to Address:**  

1. **Repositories Requiring Standardization of Translation Management:**  
   - [x] #199
   - [ ] #198
   - [ ] #197
   - [ ] #200

2. **Repositories Missing `gettext` Support (Needs Implementation):**  
   - [ ] ghostbsd/gbi  (Will most likely be deprecated.)
   - [x] https://github.com/ghostbsd/install-station/pull/7
   - [x] https://github.com/ghostbsd/setup-station/pull/3

**Tasks for Each Repository:**  

1. **For Repositories With Existing Translations:**  
   - Standardize translation management by adding commands from **update-station**:  
     - `create_translation` for creating new `.po` files.  
     - `update_translations` for updating `.po` files based on `.pot` files.  
   - Ensure all `.pot` and `.po` files are correctly integrated into the build process.  

2. **For Repositories Without `gettext` Support:**  
   - Implement `gettext` to handle translations.  
   - Add a `.pot` file for extracted messages and create initial `.po` files for supported locales.  
   - Integrate translations into the build process.  

3. **General Tasks:**  
   - Ensure the `setup.py` includes the necessary commands for managing translations.  
   - Test the translation commands in each repository to ensure they function as expected.  
   - Document the translation workflow (`create_translation`, `update_translations`) for developers in each repository's README or contributing guide.  

**Reference Implementation from update-station:**  

The **update-station** repository includes a working implementation of translation management commands. The relevant section of `setup.py` is shown below as a reference:  

```diff
index 1024411..7125516 100755
--- a/setup.py
+++ b/setup.py
@@ -1,14 +1,12 @@
 #!/usr/bin/env python
 # -*- coding: utf-8 -*-
-
 import os
 import sys
-# from glob import glob
-from setuptools import setup
+from setuptools import setup, Command, glob
 
-# import DistUtilsExtra.command.build_extra
-# import DistUtilsExtra.command.build_i18n
-# import DistUtilsExtra.command.clean_i18n
+from DistUtilsExtra.command.build_extra import build_extra
+from DistUtilsExtra.command.build_i18n import build_i18n
+from DistUtilsExtra.command.clean_i18n import clean_i18n
 
 # to update i18n .mo files (and merge .pot file into .po files) run on Linux:
 # python setup.py build_i18n -m''
@@ -18,9 +16,6 @@ __VERSION__ = '5.9'
 PROGRAM_VERSION = __VERSION__
 prefix = sys.prefix
 
-# compiling translations
-os.system("sh compile_translations.sh")
-
 
 def data_file_list(install_base, source_base):
     data = []
@@ -32,12 +27,72 @@ def data_file_list(install_base, source_base):
     return data
 
 
+class UpdateTranslationsCommand(Command):
+    """Custom command to extract messages and update .po files."""
+
+    description = 'Extract messages to .pot and update .po'
+    user_options = []  # No custom options
+
+    def initialize_options(self):
+        pass
+
+    def finalize_options(self):
+        pass
+
+    def run(self):
+        # Define paths
+        pot_file = 'po/update-station.pot'
+        po_files = glob.glob('po/*.po')
+        # Step 1: Extract messages to .pot file
+        print("Extracting messages to .pot file...")
+        os.system(f'xgettext --from-code=UTF-8 -L Python -o {pot_file} update_station/*.py update-station')
+        # Step 2: Update .po files with the new .pot file
+        print("Updating .po files with new translations...")
+        for po_file in po_files:
+            print(f"Updating {po_file}...")
+            os.system(f'msgmerge -U {po_file} {pot_file}')
+        print("Translation update complete.")
+
+
+class CreateTranslationCommand(Command):
+    """Custom command to create a new .po file for a specific language."""
+    locale = None
+    description = 'Create a new .po file for the specified language'
+    user_options = [
+        ('locale=', 'l', 'Locale code for the new translation (e.g., fr, es)')
+    ]
+
+    def initialize_options(self):
+        self.locale = None  # Initialize the locale option to None
+
+    def finalize_options(self):
+        if self.locale is None:
+            raise Exception("You must specify the locale code (e.g., --locale=fr)")
+
+    def run(self):
+        # Define paths
+        pot_file = 'po/update-station.pot'
+        pot_file = 'po/update-station.pot'
+        po_dir = 'po'
+        po_file = os.path.join(po_dir, f'{self.locale}.po')
+        # Check if the .pot file exists
+        if not os.path.exists(pot_file):
+            print("Extracting messages to .pot file...")
+            os.system(f'xgettext --from-code=UTF-8 -L Python -o {pot_file} update_station/*.py update-station')
+        # Create the new .po file
+        if not os.path.exists(po_file):
+            print(f"Creating new {po_file} for locale '{self.locale}'...")
+            os.makedirs(po_dir, exist_ok=True)
+            os.system(f'msginit --locale={self.locale} --input={pot_file} --output-file={po_file}')
+        else:
+            print(f"PO file for locale '{self.locale}' already exists: {po_file}")
+
+
 data_files = [
     (f'{prefix}/etc/xdg/autostart', ['src/update-station.desktop']),
     (f'{prefix}/share/applications', ['src/update-manager.desktop']),
     (f'{prefix}/lib/update-station', ['src/need_reboot.json', 'src/pkg_to_reinstall']),
     (f'{prefix}/etc/sudoers.d', ['src/sudoers.d/update-station']),
-    (f'{prefix}/share/locale/ru/LC_MESSAGES', ['src/locale/ru/update-station.mo'])
+    #(f'{prefix}/share/locale/ru/LC_MESSAGES', ['src/locale/ru/update-station.mo'])
 ]
 
 data_files.extend(data_file_list(f'{prefix}/share/locale', 'build/mo'))
@@ -49,9 +104,16 @@ setup(
     license='BSD',
     author='Eric Turgeon',
     url='https://github/GhostBSD/update-station/',
-    package_dir={'': 'src'},
+    package_dir={'': '.'},
     data_files=data_files,
     install_requires=['setuptools'],
-    py_modules=['updateHandler', 'update_data'],
-    scripts=['src/update-station']
+    packages=['update_station'],
+    scripts=['update-station'],
+    cmdclass={
+        'create_translation': CreateTranslationCommand,
+        'update_translations': UpdateTranslationsCommand,
+        "build": build_extra,
+        "build_i18n": build_i18n,
+        "clean": clean_i18n
+    }
 )
```

**Acceptance Criteria:**  
- All repositories have standardized translation commands (`create_translation`, `update_translations`).  
- Repositories without `gettext` now have translations implemented and integrated into the build process.  
- Translation commands are functional and tested in each repository.  
- Documentation for managing translations is available for developers.
