### ISSUE TITLE
[Epic] Complete update-station backlog

### ISSUE THREAD

**Issue by ericbsd** [ghostbsd/issues#60]
- [x] ghostbsd/update-station#20
- [x] ghostbsd/ghostbsd-src#95
- [ ] https://github.com/ghostbsd/issues/issues/56

**Comment by ericbsd** [comment]
issue moved from ghostbsd/ghostbsd-src to ghostbsd/issues
