### ISSUE TITLE
[Epic] NetworkMgr feature complete

### ISSUE THREAD

**Issue by ericbsd** [ghostbsd/issues#63]
Feature that need to be done for better user experience:
- [x] https://github.com/ghostbsd/networkmgr/issues/29
- [x] https://github.com/ghostbsd/networkmgr/issues/28
- [ ] https://github.com/ghostbsd/networkmgr/issues/25
- [ ] https://github.com/ghostbsd/ghostbsd-src/issues/111

**Comment by ericbsd** [comment]
issue moved from ghostbsd/ghostbsd-src to ghostbsd/issues

**Comment by ericbsd** [comment]
Not using this anymore.
