### ISSUE TITLE
[Epic] Add OEM installtion support

### ISSUE THREAD

**Issue by ericbsd** [ghostbsd/issues#65]
List of tasks to prepare the OEM installation for future ISO.

- [x] https://github.com/ghostbsd/ghostbsd-build/pull/143
- [x] ghostbsd/ghostbsd-src#104
- [ ] https://github.com/ghostbsd/issues/issues/75
- [ ] ghostbsd/issues#64
- [x] ghostbsd/ghostbsd-src#106
- [x] ghostbsd/ghostbsd-src#107
- [x] ghostbsd/ghostbsd-src#108
- [x] ghostbsd/ghostbsd-src#109
- [x] ghostbsd/ghostbsd-src#214

**Note:** OEM installation will only be supported in the Official ISO.

**Comment by ericbsd** [comment]
issue moved from ghostbsd/ghostbsd-src to ghostbsd/issues

**Comment by ericbsd** [comment]
The installer and the initial work setup station are completed. Now it is testing time. I am closing this. We will create PR and tickets for issues we find.
